Controllers/SignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLLaptop.Models;

namespace QLLaptop.Controllers
{
    public class SignController : Controller
    {
        //
        // GET: /Sign/
        SanPhamDBDataContext data = new SanPhamDBDataContext();
        
        [HttpGet]
        public ActionResult SignUp()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SignUp(FormCollection collection,KHACHHANG kh)
        {
            var Usernamex = collection["Username"];
            var IDx = collection["ID"];
            var Passwordx = collection["Password"];
            var Emailx = collection["Email"];
            var Addressx = collection["Address"];
            var Phonex = collection["Phone"];
            kh.HoTen = Usernamex;
            kh.Taikhoan = IDx;
            kh.Matkhau = Passwordx;
            kh.Email = Emailx;
            kh.DiachiKH = Addressx;
            kh.DienthoaiKH = Phonex;
            data.KHACHHANGs.InsertOnSubmit(kh);
            data.SubmitChanges();
            return RedirectToAction("Login");
            //return this.SignUp();
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(FormCollection collection)
        {
            var IDx = collection["ID"];
            var Passwordx = collection["Password"];
            KHACHHANG kh = data.KHACHHANGs.SingleOrDefault(n => n.Taikhoan == IDx && n.Matkhau == Passwordx);
            if (kh != null)
            {
                Session["Taikhoan"] = kh;
                return RedirectToAction("Index", "MyWeb");
            }
            else
                ViewBag.Thongbao = "ID or Password is incorrect";
            return View();
        }
        public ActionResult TH()
        {
            var Thuonghieu = from th in data.THUONGHIEUs select th;
            return PartialView(Thuonghieu);
        }
        public ActionResult LabelUser()
        {
            return PartialView();
        }
        public ActionResult Logout()
        {
            Session["Taikhoan"] = null;
            return RedirectToAction("Index", "MyWeb");
        }
    }
}

Views/Sign/LabelUser.cshtml
@using QLLaptop.Models;
@{
    KHACHHANG kh = (KHACHHANG)Session["TaiKhoan"];
}
@if(kh == null)
{
    <li><a href="@Url.Action("Login","Sign")">đăng nhập</a></li> 
	<li><a href="@Url.Action("SignUp","Sign")">đăng ký</a></li>
}
else
{
    //<li><a href="@Url.Action("Index","MyWeb")">Welcome!@kh.Taikhoan</a></li>
    @*<li><h5 style="color:red;text-align:center">Welcome!@kh.Taikhoan</h5></li>*@
    <li><h5 style="color: red; text-align: center; text-transform: uppercase; ">Hi ! @kh.Taikhoan</h5></li>
    <li><a href="@Url.Action("Logout","Sign")">Đăng xuất</a></li>
}

Views/Sign/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/login_user.cshtml";
}

<h2></h2>

<div class="w3_login">
    <h3>Đăng nhập & Đăng ký</h3>
    <div class="w3_login_module">
        <div class="module form-module">
            <div class="toggle">
                <i class="fa fa-times fa-pencil"></i>
                <div class="tooltip">Click Me</div>
            </div>
            <div class="form">
                <h4 style="color:red;text-align:center">@ViewBag.Thongbao</h4>
                <h2>Đăng nhập với tài khoản có sẵn</h2>
                <form action="@Url.Action("Login","Sign")" method="post">
                    <input type="text" name="ID" placeholder="ID" required="">
                    <input type="password" name="Password" placeholder="Password" required="">
                    <input type="submit" value="Đăng nhập">
                </form>
            </div>
            <div class="form">
                <h2>Tạo tài khoản</h2>
                <form action="@Url.Action("SignUp","Sign")" method="post">
                    <input type="text" name="Username" placeholder="Username" required="">
                    <input type="text" name="ID" placeholder="ID" required="">
                    <input type="password" name="Password" placeholder="Password" required="">
                    <input type="email" name="Email" placeholder="Email Address" @*required=""*@>
                    <input type="text" name="Address" placeholder="User Address" @*required=""*@>
                    <input type="text" name="Phone" placeholder="Phone Number" @*required=""*@>
                    <input type="submit" value="Đăng ký">
                </form>
            </div>
            <div class="cta"><a href="#">Bạn quên mật khẩu</a></div>
        </div>
    </div>
    <script>
        $('.toggle').click(function () {
            // Switches the Icon
            $(this).children('i').toggleClass('fa-pencil');
            // Switches the forms
            $('.form').animate({
                height: "toggle",
                'padding-top': 'toggle',
                'padding-bottom': 'toggle',
                opacity: "toggle"
            }, "slow");
        });
    </script>
</div>

Views/Sign/SignUp.cshtml
@{
    ViewBag.Title = "SignUp";
    Layout = "~/Views/Shared/login_user.cshtml";
}

<h2></h2>

<div class="w3_login">
    <h3>Sign In & Sign Up</h3>
    <div class="w3_login_module">
        <div class="module form-module">
            <div class="toggle">
                <i class="fa fa-times fa-pencil"></i>
                <div class="tooltip">Click Me</div>
            </div>
            <div class="form">
                <h2>Create an account</h2>
                <form action="@Url.Action("SignUp","Sign")" method="post">
                    <input type="text" name="Username" placeholder="Username" required="">
                    <input type="text" name="ID" placeholder="ID" required="">
                    <input type="password" name="Password" placeholder="Password" required="">
                    <input type="email" name="Email" placeholder="Email Address" @*required=""*@>
                    <input type="text" name="Address" placeholder="User Address" @*required=""*@>
                    <input type="text" name="Phone" placeholder="Phone Number" @*required=""*@>
                    <input type="submit" value="Register">
                </form>
            </div>
            <div class="form">
                <h2>Login to your account</h2>
                <form action="@Url.Action("Login","Sign")" method="post">
                    <input type="text" name="ID" placeholder="ID" required="">
                    <input type="password" name="Password" placeholder="Password" required="">
                    <input type="submit" value="Login">
                </form>
            </div>
            @*<div class="form">
                <h2>Create an account</h2>
                <form action="#" method="post">
                    <input type="text" name="Username" placeholder="Username" required="">
                    <input type="password" name="Password" placeholder="Password" required="">
                    <input type="email" name="Email" placeholder="Email Address" required="">
                    <input type="text" name="Phone" placeholder="Phone Number" required="">
                    <input type="submit" value="Register">
                </form>
            </div>*@
            <div class="cta"><a href="#">Forgot your password?</a></div>
        </div>
    </div>
    <script>
        $('.toggle').click(function () {
            // Switches the Icon
            $(this).children('i').toggleClass('fa-pencil');
            // Switches the forms
            $('.form').animate({
                height: "toggle",
                'padding-top': 'toggle',
                'padding-bottom': 'toggle',
                opacity: "toggle"
            }, "slow");
        });
    </script>
</div>

Views/Sign/TH.cshtml
@model IEnumerable<QLLaptop.Models.THUONGHIEU>
@foreach (var item in Model)
{
    <li><a href="@Url.Action("SPtheoTH", "MyWeb", new {id=item.MaTH})">@item.TenTH</a></li>
}