Controllers/MyWebController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLLaptop.Models;

using PagedList;
using PagedList.Mvc;
using System.Net.Mail;
namespace QLLaptop.Controllers
{
    public class MyWebController : Controller
    {
        //
        // GET: /MyWeb/
        SanPhamDBDataContext data = new SanPhamDBDataContext();

        private List<SANPHAM> take(int count)
        {
            return data.SANPHAMs.Take(count).ToList();
        }
        public ActionResult Index(int ? page)
        {
            int pageSize = 4;
            int pageNum = (page ?? 1);
            var Sanpham = take(4);//from sp in data.SANPHAMs select sp;
            return View(Sanpham.ToPagedList(pageNum,pageSize));
        }
        public ActionResult TH()
        {
            var Thuonghieu = from th in data.THUONGHIEUs select th;
            return PartialView(Thuonghieu);
        }
        public ActionResult SPtheoTH(int id,int ? page)
        {
            int pageSize = 4;
            int pageNum = (page ?? 1);
            var Sanpham = from sp in data.SANPHAMs where sp.MaTH == id select sp;
            return View(Sanpham.ToPagedList(pageNum, pageSize));
        }
        public ActionResult CTSP(int id)
        {
            var Sanpham = from sp in data.SANPHAMs where sp.MaSP == id select sp;
            return View(Sanpham.Single());
        }
        public ActionResult THSP(int id)
        {
            var Thuonghieu = from th in data.THUONGHIEUs where th.MaTH == id select th;
            return PartialView(Thuonghieu);
        }
        public ActionResult Map()
        {
            return View();
        }
        public ActionResult SearchSP(string keywords, int? page)
        {
            int pageSize = 4;
            int pageNum = (page ?? 1);
            var Sanpham = from sp in data.SANPHAMs where  sp.TenSP.Contains(keywords) select sp;
            return View(Sanpham.ToPagedList(pageNum, pageSize));
        }


        [HttpGet]
        public ActionResult SendMail()
        {
            return PartialView();
        }
        [HttpPost]

        public ActionResult SendMail(FormCollection collect)
        {
            var HoTen = collect["Name"];
            var EmailLayVe = collect["Email"];
            var TieuDe = collect["Subject"];
            var NoiDung = collect["Message"];
            var Email = new SmtpClient("smtp.gmail.com", 25)
            {
                Credentials = new System.Net.NetworkCredential("dominhtri1996ntl@gmail.com", "cbkgndcszq123456"),
                EnableSsl = true
            };
            var ThongDiep = new MailMessage();
            ThongDiep.From = new MailAddress(EmailLayVe, "Gửi Từ: " + HoTen + "Từ Mail: " + EmailLayVe, System.Text.Encoding.UTF8);
            ThongDiep.To.Add("dominhtri1996_ntl@yahoo.com");
            ThongDiep.Subject = TieuDe;
            ThongDiep.Body = NoiDung;
            Email.Send(ThongDiep);
            ViewData["ThanhCong"] = "Send mail thành công";
            return RedirectToAction("Map");
        }
    }
}

Views/MyWeb/CTSP.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/index_user.cshtml";
}

<h2>Thong tin san pham</h2>

<!-- for-mobile-apps -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Grocery Store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript">
    addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
           function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //for-mobile-apps -->
<link href="/123/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
<link href="/123/css/style.css" rel="stylesheet" type="text/css" media="all" />
<!-- font-awesome icons -->
<link href="/123/css/font-awesome.css" rel="stylesheet" type="text/css" media="all" />
<!-- //font-awesome icons -->
<!-- js -->
<script src="/123/js/jquery-1.11.1.min.js"></script>
<!-- //js -->
<script src='/123/js/okzoom.js'></script>
<script>
    $(function () {
        $('#example').okzoom({
            width: 150,
            height: 150,
            border: "1px solid black",
            shadow: "0 0 5px #000"
        });
    });
</script>
<link href='//fonts.googleapis.com/css?family=Ubuntu:400,300,300italic,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<!-- start-smoth-scrolling -->
<script type="text/javascript" src="/123/js/move-top.js"></script>
<script type="text/javascript" src="/123/js/easing.js"></script>
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $(".scroll").click(function (event) {
            event.preventDefault();
            $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1000);
        });
    });
</script>


<div class="agileinfo_single">
    <h5>@Model.TenSP</h5>
    <div class="col-md-4 agileinfo_single_left">
        <img id="example" src="/123/Hinh/@Model.Anhbia" alt=" " class="img-responsive" />
    </div>
    <div class="col-md-8 agileinfo_single_right">
        <div class="rating1">
            <span class="starRating">
                <input id="rating5" type="radio" name="rating" value="5" checked>
                <label for="rating5">5</label>
                <input id="rating4" type="radio" name="rating" value="4">
                <label for="rating4">4</label>
                <input id="rating3" type="radio" name="rating" value="3">
                <label for="rating3">3</label>
                <input id="rating2" type="radio" name="rating" value="2">
                <label for="rating2">2</label>
                <input id="rating1" type="radio" name="rating" value="1">
                <label for="rating1">1</label>
            </span>
        </div>
        <div class="w3agile_description">
            <h4>Description :</h4>
            <p>@Model.Mota</p>
            <!-- khuc nay like share fb n^^ếu mu^^ốn thay thanh` cua minh th``i Request.Url.AbsoluteUri -->
            <p><div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div></p>
        </div>
        <div class="snipcart-item block">
            <div class="snipcart-thumb agileinfo_single_right_snipcart">
                <h4>@string.Format("{0:0,0}",Model.Giaban) VND</h4>
            </div>
            <div class="snipcart-details agileinfo_single_right_details">
                <form action="@Url.Action("ThemGioHang","GioHang",new{@iMaLT = @Model.MaSP,@strURL = Request.Url.ToString()})" method="post">
                    <fieldset>
                        @*<input type="hidden" name="cmd" value="_cart" />
                        <input type="hidden" name="add" value="1" />
                        <input type="hidden" name="business" value=" " />
                        <input type="hidden" name="item_name" value="@Model.TenSP" />
                        <input type="hidden" name="amount" value="@Model.Giaban" />
                        <input type="hidden" name="discount_amount" value="" />
                        <input type="hidden" name="currency_code" value="VND" />
                        <input type="hidden" name="return" value=" " />
                        <input type="hidden" name="cancel_return" value=" " />*@
                        <input type="submit" name="submit" value="Add to cart" class="button" />
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
    <div class="clearfix"> </div>
    @*<div class="fb-comments" style="margin-top: 20px;" data-href="@Request.Url.AbsoluteUri" data-width="870" data-numposts="5"></div>*@
</div>

Views/MyWeb/Index.cshtml
@using QLLaptop.Models
@using PagedList.Mvc;
@model PagedList.PagedList<SANPHAM>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/index_user.cshtml";
}

<center>
    <div id="Leephantrang" style="margin-top: -20px">
        @*Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount*@
        <div class="MenuTrang">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
        </div>
        <style>
            .MenuTrang li {
                display: inline;
            }
        </style>
    </div>
</center>

@foreach (var item in Model)
{
    <div class="col-md-3 top_brand_left">
        <div class="hover14 column">
            <div class="agile_top_brand_left_grid">
                <!--<div class="tag"><img src="/123/images/tag.png" alt=" " class="img-responsive" /></div>-->
                <div class="agile_top_brand_left_grid1">
                    <figure>
                        <div class="snipcart-item block">
                            <div class="snipcart-thumb">
                                <a href="@Url.Action("CTSP", "MyWeb", new {id=item.MaSP})"><img style="height:200px" title=" " alt=" " src="/123/Hinh/@item.Anhbia" /></a>
                                <p>@item.TenSP</p>
                                <p>Cost</p>
                                <h4>@string.Format("{0:0,0}", item.Giaban) VND</h4>
                            </div>
                            <div class="snipcart-details top_brand_home_details">
                                <form action="@Url.Action("CTSP", "MyWeb", new {id=item.MaSP})" method="post">
                                    <fieldset>
                                        @*<input type="hidden" name="cmd" value="_cart" />
                                            <input type="hidden" name="add" value="1" />
                                            <input type="hidden" name="business" value=" " />
                                            <input type="hidden" name="item_name" value="@item.TenSP" />
                                            <input type="hidden" name="amount" value="@item.Giaban" />
                                            <input type="hidden" name="discount_amount" value="" />
                                            <input type="hidden" name="currency_code" value="VND" />
                                            <input type="hidden" name="return" value=" " />
                                            <input type="hidden" name="cancel_return" value=" " />*@
                                        <input type="submit" name="submit" value="Show details" class="button" />
                                    </fieldset>
                                </form>
                            </div>
                        </div>
                    </figure>
                </div>
            </div>
        </div>
    </div>
}

Views/MyWeb/Map.cshtml
@{
    ViewBag.Title = "Map";
    Layout = "~/Views/Shared/mail.cshtml";
}

<div class="mail">
    <h3>Liên hệ chúng tôi</h3>
    <div class="agileinfo_mail_grids">
        <div class="col-md-4 agileinfo_mail_grid_left">
            <ul>
                <li><i class="fa fa-home" aria-hidden="true"></i></li>
                <li>Địa chỉ<span>Tân Sơn Nhì, Tân Phú, TPHCM</span></li>
            </ul>
            <ul>
                <li><i class="fa fa-envelope" aria-hidden="true"></i></li>
                <li>Email<span>nquocquan@gmail.com</span></li>
            </ul>
            <ul>
                <li><i class="fa fa-phone" aria-hidden="true"></i></li>
                <li>Điện thoại<span>+84 167.750.1.567</span></li>
            </ul>
        </div>
        <div class="col-md-8 agileinfo_mail_grid_right">
            <form action="@Url.Action("SendMail", "MyWeb")" method="post" name="collect">
                <div class="col-md-6 wthree_contact_left_grid">
                    <input type="text" name="Name" value="Name*" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Name*';}" required="">
                    <input type="email" name="Email" value="Email*" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email*';}" required="">
                </div>
                <div class="col-md-6 wthree_contact_left_grid">
                    <input type="text" name="Telephone" value="Telephone*" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Telephone*';}" required="">
                    <input type="text" name="Subject" value="Subject*" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Subject*';}" required="">
                </div>
                <div class="clearfix"> </div>
                <textarea name="Message" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Message...';}" required="">Message...</textarea>
                <input type="submit" value="Submit">
                <input type="reset" value="Clear">
            </form>
        </div>
        <div class="clearfix"> </div>
    </div>
</div>
<div class="map-w3">
    <style>
        #map {
            width: 100%;
            height: 400px;
        }
    </style>

    <div id="map"></div>
    <button class="btn btn-primary" style="" onclick="timDuongDi()">Tìm đường đi</button>
    <script>
        function initMap() {
            var latlng = new google.maps.LatLng(10.802145, 106.715001); //Tọa độ cửa hàng
            var map = new google.maps.Map(document.getElementById('map'), {
                center: latlng,
                zoom: 16 //Độ phóng to của bản đồ
            });
            var marker = new google.maps.Marker({
                position: latlng,
                map: map,
                title: "Your Title" //Tên hiển thị khi đưa chuột vào địa điểm
            });
        }
        function timDuongDi() {
            var latlng = new google.maps.LatLng(10.802145, 106.715001); //Vị trí của cửa hàng
            var map = new google.maps.Map(document.getElementById('map'), {
                center: latlng,
                zoom: 16
            });
            var infoWindow = new google.maps.InfoWindow({ map: map });
            // Try HTML5 geolocation.
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function (position) {
                    var pos = {
                        lat: position.coords.latitude,
                        lng: position.coords.longitude
                    };
                    infoWindow.setPosition(pos);
                    infoWindow.setContent('Vị trí của bạn');
                    map.setCenter(pos);
                    var directionsDisplay = new google.maps.DirectionsRenderer({
                        map: map
                    });
                    var request = {
                        destination: latlng,
                        origin: pos,
                        travelMode: google.maps.TravelMode.DRIVING
                    };
                    var directionsService = new google.maps.DirectionsService();
                    directionsService.route(request, function (response, status) {
                        if (status == google.maps.DirectionsStatus.OK) {
                            // Display the route on the map.
                            directionsDisplay.setDirections(response);
                        }
                    });
                }, function () {
                    handleLocationError(true, infoWindow, map.getCenter());
                });
            } else {
                // Browser doesn't support Geolocation
                handleLocationError(false, infoWindow, map.getCenter());
            }
        }
        function handleLocationError(browserHasGeolocation, infoWindow, pos) {
            infoWindow.setPosition(pos);
            infoWindow.setContent(browserHasGeolocation ?
                                  'Error: The Geolocation service failed.' :
                                  'Error: Your browser doesn\'t support geolocation.');
        }
    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB57VYYya-drlJKiiVGjJh8_sXiFWmKXEo&callback=initMap">
    </script>

</div>

Views/MyWeb/SPtheoTH.cshtml
@using QLLaptop.Models
@using PagedList.Mvc;
@model PagedList.PagedList<SANPHAM>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/index_user.cshtml";
}

<h2></h2>

<center>
    <div id="Leephantrang" style="margin-top: -20px">
        @*Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount*@
        <div class="MenuTrang">
            @Html.PagedListPager(Model, page => Url.Action("SPtheoTH", new { page = page }))
        </div>
        <style>
            .MenuTrang li {
                display: inline;
            }
        </style>
    </div>
</center>
@Html.Action("THSP", "MyWeb")
@foreach(var item in Model)
{
    <div class="col-md-3 top_brand_left">
        <div class="hover14 column">
            <div class="agile_top_brand_left_grid">
                <!--<div class="tag"><img src="/123/images/tag.png" alt=" " class="img-responsive" /></div>-->
                <div class="agile_top_brand_left_grid1">
                    <figure>
                        <div class="snipcart-item block">
                            <div class="snipcart-thumb">
                                <a href="@Url.Action("CTSP", "MyWeb", new {id=item.MaSP})"><img style="height:200px" title=" " alt=" " src="/123/Hinh/@item.Anhbia" /></a>
                                <p>@item.TenSP</p>
                                <p>Cost</p>
                                <h4>@string.Format("{0:0,0}",item.Giaban) VND</h4>
                            </div>
                            <div class="snipcart-details top_brand_home_details">
                                <form action="@Url.Action("CTSP", "MyWeb", new {id=item.MaSP})" method="post">
                                    <fieldset>
                                        @*<input type="hidden" name="cmd" value="_cart" />
                                        <input type="hidden" name="add" value="1" />
                                        <input type="hidden" name="business" value=" " />
                                        <input type="hidden" name="item_name" value="@item.TenLT" />
                                        <input type="hidden" name="amount" value="@item.Giaban" />
                                        <input type="hidden" name="discount_amount" value="" />
                                        <input type="hidden" name="currency_code" value="USD" />
                                        <input type="hidden" name="return" value=" " />
                                        <input type="hidden" name="cancel_return" value=" " />*@
                                        <input type="submit" name="submit" value="Show details" class="button" />
                                    </fieldset>
                                </form>
                            </div>
                        </div>
                    </figure>
                </div>
            </div>
        </div>
    </div>
}

Views/MyWeb/SearchSP.cshtml
@using QLLaptop.Models
@using PagedList.Mvc;
@model PagedList.PagedList<SANPHAM>



@{
    ViewBag.Title = "Tìm kiếm sản phẩm";
    Layout = "~/Views/Shared/index_user.cshtml";
    var key = HttpContext.Current.Request.QueryString["keywords"];
}


<center>
    <div id="Leephantrang" style="margin-top: -20px">
        @*Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount*@
        <div class="MenuTrang">
            @Html.PagedListPager(Model, page => Url.Action("SearchSP", new { keywords = key , page = page }))
        </div>
        <style>
            .MenuTrang li {
                display: inline;
            }
        </style>
    </div>
</center>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TenSP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Giaban)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mota)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Anhbia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Soluongton)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenSP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Giaban)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mota)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Anhbia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Soluongton)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
    }

    </table>*@
<div id="sp">
@if(Model.Count < 1)
    {
    <h1>không thấy kết quả nào! </h1>
    }else{
    foreach (var item in Model)
    {
        <div class="col-md-3 top_brand_left">
					<div class="hover14 column">
						<div class="agile_top_brand_left_grid">
							<!--<div class="tag"><img src="/123/images/tag.png" alt=" " class="img-responsive" /></div>-->
							<div class="agile_top_brand_left_grid1">
								<figure>
									<div class="snipcart-item block" >
										<div class="snipcart-thumb">
                                            <a href="@Url.Action("CTSP", "MyWeb", new {id=item.MaSP})"><img style="height:200px" title=" " alt=" " src="/123/Hinh/@item.Anhbia" /></a>		
											<p>@item.TenSP</p>
                                            <p>Cost</p>
											<h4>@string.Format("{0:0,0}",item.Giaban) VND</h4>
										</div>
										<div class="snipcart-details top_brand_home_details">
                                            <form action="@Url.Action("CTSP", "MyWeb", new {id=item.MaSP})" method="post">
                                                <fieldset>
                                                    @*<input type="hidden" name="cmd" value="_cart" />
                                                    <input type="hidden" name="add" value="1" />
                                                    <input type="hidden" name="business" value=" " />
                                                    <input type="hidden" name="item_name" value="@item.TenSP" />
                                                    <input type="hidden" name="amount" value="@item.Giaban" />
                                                    <input type="hidden" name="discount_amount" value="" />
                                                    <input type="hidden" name="currency_code" value="VND" />
                                                    <input type="hidden" name="return" value=" " />
                                                    <input type="hidden" name="cancel_return" value=" " />*@
                                                    <input type="submit" name="submit" value="Show details" class="button" />
                                                </fieldset>
                                            </form>
										</div>
									</div>
								</figure>
							</div>
						</div>
					</div>
				</div>
    }

}
</div>

Views/MyWeb/TH.cshtml
@model IEnumerable<QLLaptop.Models.THUONGHIEU>
@foreach(var item in Model)
{
    <li><a href="@Url.Action("SPtheoTH", "MyWeb", new {id=item.MaTH})">@item.TenTH</a></li>
}

Views/MyWeb/THSP.cshtml
@model IEnumerable<QLLaptop.Models.THUONGHIEU>
@foreach (var item in Model)
{
    <h1 style="color:red; margin-bottom:30px;">@item.TenTH</h1>
}